# Generated by Django 4.2.18 on 2025-01-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndOfDayReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
            ],
        ),
    ]
