# Generated by Django 4.2.18 on 2025-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_endofdayreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="report_file",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
    ]
